spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GaozyDev/ConfigCloud.git
          username: 670453367@qq.com
          password: MhrkDByiPY5snfa
  rabbitmq:
    host: 120.46.136.163
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
