spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GaozyDev/ConfigCloud.git
          username: 670453367@qq.com
          password: MhrkDByiPY5snfa
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"